version: '3.8'

networks:
  default:
    name: ssb_csp-ce-net
    external: true

services:
  domain_all:
    image: brainiac/event-mesh:0.0.1
    entrypoint: ["./start_up_no_domain.sh"]
    environment:
    - DESTINATION=ssb-kafka-1:9092
