version: '3.8'

networks:
  default:
    name: ssb_csp-ce-net
    external: true

services:
  domain_IoT:
    image: brainiac/event-mesh:0.0.1
    entrypoint: ["./start_up_domain_3_IoT.sh"]
    environment:
    - DESTINATION=localhost:9093

  refdatadb:
    image: brainiac/event-mesh-refdata:0.0.1
    container_name: domain_shared-refdata
    hostname: refdatadb
    environment:
      - POSTGRES_PASSWORD=Supersecret1
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_DB=testdb
    ports:
      - 6666:5432
